BaseURL: "http://vidhance.com"
languageCode: "en-us"
title: "Vidhance"
blackfriday:
  extensions:
    - hardLineBreak
theme: hugo-vidhance-theme
MetaDataFormat: "yaml"
menu:
  main:
    - name: "News"
      weight: 15
      URL: "/newspost/"
    - name: "Solutions"
      weight: 20
      URL: "/solutions/"
    - name: "Technology"
      weight: 21
      URL: "/technology/"
    - name: "Vidhancemobile.com →"
      weight: 50
      URL: "http://vidhancemobile.com"
